# ===============================
# Application Name
# ===============================
spring.application.name=api-gateway

# ===============================
# Server Port
# ===============================
server.port=8085

# ===============================
# Redis Configuration (Rate Limiter)
# ===============================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ===============================
# Gateway Routes
# ===============================

spring.cloud.gateway.routes[0].id=order-service
spring.cloud.gateway.routes[0].uri=lb://FEIGN-ORDER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/order/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[0].filters[1]=RequestRateLimiter=redis-rate-limiter.replenishRate=5,redis-rate-limiter.burstCapacity=5,key-resolver=#{@ipKeyResolver}

spring.cloud.gateway.routes[1].id=payment-service
spring.cloud.gateway.routes[1].uri=lb://FEIGN-PAYMENT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/payment/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

# ===============================
# Eureka
# ===============================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# ===============================
# Actuator
# ===============================

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
